// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_stan_fit4DM_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4EFDM_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4EFDM_hyper_w_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4FDM2_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4Multinomial_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4DM_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4DM_mod, 0},
    {"_rcpp_module_boot_stan_fit4EFDM_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4EFDM_mod, 0},
    {"_rcpp_module_boot_stan_fit4EFDM_hyper_w_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4EFDM_hyper_w_mod, 0},
    {"_rcpp_module_boot_stan_fit4FDM2_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4FDM2_mod, 0},
    {"_rcpp_module_boot_stan_fit4Multinomial_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4Multinomial_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_EFDMReg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
